# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export EDITOR="vim"

# set to random for a random theme
ZSH_THEME="esp"
CASE_SENSITIVE="true"

# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# ENABLE_CORRECTION="true"

plugins=(
    git autojump tmux
    colored-man command-not-found
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

if [ -f ~/.sh_aliases ]; then
    source ~/.sh_aliases
fi

if [ -f $HOME/.local-zshrc.zsh ]; then
    source .local-zshrc.zsh
fi

if [ -d $HOME/bin ]; then
    export PATH="$PATH:$HOME/bin"
fi

if [ -d $HOME/.local/bin ]; then
    export PATH="$PATH:$HOME/.local/bin"
fi
