# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# set to random for a random theme
ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true"

# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# ENABLE_CORRECTION="true"

plugins=(
    git autojump
    colored-man command-not-found
    web-search tmux
    zsh-syntax-highlighting
)

# User configuration

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"

source $ZSH/oh-my-zsh.sh

if [ -f ~/.sh_aliases ]; then
    source ~/.sh_aliases
fi

if [ -d $HOME/bin ]; then
    export PATH="$PATH:$HOME/bin"
fi

if [ -d $HOME/.local/bin ]; then
    export PATH="$PATH:$HOME/.local/bin"
fi

if [ -f /afs/club.cc.cmu.edu/contrib/etc/zshrc ]; then
    source /afs/club.cc.cmu.edu/contrib/etc/bashrc
fi

if [ -d /afs/cs.cmu.edu/academic/class/15410-f15/bin ]; then
    export PATH="$PATH:/afs/cs.cmu.edu/academic/class/15410-f15/bin"
fi
